export const products = [
  {
    id: 1,
    subtitle: "Intensive Bootcamp",
    title: "Programming Laravel",
    description: "Getting Started with Laravel 9",
    batch: "September 2022",
    mentor: ["William Hartono", "Farel Proyoga"],
    normal_price: "Rp 2.600.000",
    final_price: "Rp 560.000",
    is_discount: true,
  },
  {
    id: 2,
    subtitle: "Intensive Bootcamp",
    title: "Programming Laravel",
    description: "Getting Started with Laravel 9",
    batch: "September 2022",
    mentor: ["William Hartono", "Farel Proyoga"],
    normal_price: "Rp 2.600.000",
    final_price: "Rp 560.000",
    is_discount: true,
  },
  {
    id: 3,
    subtitle: "Intensive Bootcamp",
    title: "Programming Laravel",
    description: "Getting Started with Laravel 9",
    batch: "September 2022",
    mentor: ["William Hartono", "Farel Proyoga"],
    normal_price: "Rp 2.600.000",
    final_price: "Rp 560.000",
    is_discount: true,
  },
  {
    id: 4,
    subtitle: "Intensive Bootcamp",
    title: "Programming Laravel",
    description: "Getting Started with Laravel 9",
    batch: "September 2022",
    mentor: ["William Hartono", "Farel Proyoga"],
    normal_price: "Rp 2.600.000",
    final_price: "Rp 560.000",
    is_discount: true,
  },
  {
    id: 5,
    subtitle: "Intensive Bootcamp",
    title: "Programming Laravel",
    description: "Getting Started with Laravel 9",
    batch: "September 2022",
    mentor: ["William Hartono", "Farel Proyoga"],
    normal_price: "Rp 2.600.000",
    final_price: "Rp 560.000",
    is_discount: true,
  },
  {
    id: 6,
    subtitle: "Intensive Bootcamp",
    title: "Programming Laravel",
    description: "Getting Started with Laravel 9",
    batch: "September 2022",
    mentor: ["William Hartono", "Farel Proyoga"],
    normal_price: "Rp 2.600.000",
    final_price: "Rp 560.000",
    is_discount: true,
  },
  {
    id: 7,
    subtitle: "Intensive Bootcamp",
    title: "Programming Laravel",
    description: "Getting Started with Laravel 9",
    batch: "September 2022",
    mentor: ["William Hartono", "Farel Proyoga"],
    normal_price: "Rp 2.600.000",
    final_price: "Rp 560.000",
    is_discount: true,
  },
  {
    id: 8,
    subtitle: "Intensive Bootcamp",
    title: "Programming Laravel",
    description: "Getting Started with Laravel 9",
    batch: "September 2022",
    mentor: ["William Hartono", "Farel Proyoga"],
    normal_price: "Rp 2.600.000",
    final_price: "Rp 560.000",
    is_discount: true,
  },
  {
    id: 9,
    subtitle: "Intensive Bootcamp",
    title: "Programming Laravel",
    description: "Getting Started with Laravel 9",
    batch: "September 2022",
    mentor: ["William Hartono", "Farel Proyoga"],
    normal_price: "Rp 2.600.000",
    final_price: "Rp 560.000",
    is_discount: true,
  },
  {
    id: 10,
    subtitle: "Intensive Bootcamp",
    title: "Programming Laravel",
    description: "Getting Started with Laravel 9",
    batch: "September 2022",
    mentor: ["William Hartono", "Farel Proyoga"],
    normal_price: "Rp 2.600.000",
    final_price: "Rp 560.000",
    is_discount: true,
  },
  {
    id: 11,
    subtitle: "Intensive Bootcamp",
    title: "Programming Laravel",
    description: "Getting Started with Laravel 9",
    batch: "September 2022",
    mentor: ["William Hartono", "Farel Proyoga"],
    normal_price: "Rp 2.600.000",
    final_price: "Rp 560.000",
    is_discount: true,
  },
  {
    id: 12,
    subtitle: "Intensive Bootcamp",
    title: "Programming Laravel",
    description: "Getting Started with Laravel 9",
    batch: "September 2022",
    mentor: ["William Hartono", "Farel Proyoga"],
    normal_price: "Rp 2.600.000",
    final_price: "Rp 560.000",
    is_discount: true,
  },
];
